date = { start = , end = }
title = { en = "", fr = "" }
icon = ""
media = []

[links]
github = ""

[tags]
en = []
fr = []

[summary]
en = ""
fr = ""

[resume_lines]
en = [

]
fr = [

]

[body]
en = """

"""
fr = """

"""
