[title]
en = "Experience"
fr = "Expérience"

[body]
en = """
While experience with projects is important, internship experience teaches not only technical skills but also soft skills crucial for software engineers.

Below you will find information about my internships and other forms of experience as part of a team.
"""
fr = """
Bien que l'expérience avec des projets est importante, de l'expérience avec des stages permet d'apprendre non seulement des compétences techniques mais aussi des compétences générales cruciales pour les ingénieurs logiciels.

Ci-dessous vous trouverez plus d'information à propos de mes stages et autres formes d'expéience en tant que membre d'équipes.
"""
