date = { start = 2021-09-01, end = 2025-05-01 }
title = { en = "B.Eng. Software Engineering Co-op", fr = "Génie logiciel co-op (B.Eng.)" }
icon = "McGill_logo.png"

[summary]
en = ".."
fr = ".."

[resume_lines]
en = [
  "CGPA: 3.96/4.0",
  "Selected for the Dean's Honour List for my first and second years.",
  "Recipient of multiple merit-based scholarships, including the Les Vadasz Award in Engineering and the Faculty of Engineering Scholarship.",
]
fr = [
  "Moyenne cumulative: 3.96/4.0",
  "Séléctionné pour la « Dean's Honour List » pour ma première et deuxième année.",
  "Récipiendaire de plusieurs bourses basées sur le mérite académique, dont le « Les Vadasz Award in Engineering » et le « Faculty of Engineering Scholarship ».",
]

[body]
en = """
It seems that every time I progress in my education curriculum, I find myself enjoying more the position I'm in. When I went from high school to college/CEGEP, I enjoyed the additional freedom and the more advanced topics I was learning about. And when I got to university, I knew I was on the right track; what was previously a hobby of mine that I used to get away from the stress of school was now the main focus of my studies, and was what professors were teaching me!

In my first semester, I enrolled in the McGill Artificial Intelligence Society's "MAIS 202" bootcamp, an accelerated introduction to AI and ML. I later joined McGill's robotics team, and worked on a Mars rover. However, I soon found out that I was more interested in game development, and I joined the GameDev McGill club.

Each semester, I am more experienced than the last and I learn about the inner workings of different areas and technologies. When I look back at my previous work experiences and projects, I am amazed at how far I've come and how much I've learned!
"""
fr = """
Il semble que chaque fois que je progresse dans mon éducation, j'apprécie de plus en plus la position dans laquelle je me trouve. Quand j'ai été du secondaire au cégep, j'ai apprécié la liberté et les sujets plus poussés que j'ai appris. Puis quand je suis arrivé à l'université, j'ai su que j'étais au bon endroit. Ce qui était avant un passe-temps était maintenant le sujet principal de mes études et était ce que les professeurs m'enseignaient!

Dans mon premier semestre, je me suis inscrit à « MAIS 202 », un cours d'introduction à l'IA et au machine learning offert par la société d'IA de McGill. Plus tard, j'ai joint l'équipe de robotique de McGill et j'ai travaillé sur un rover. Par contre, je me suis rendu compte que j'étais plus intéressé par le développement de jeux vidéos et j'ai alors joint le club GameDev McGill.

Chaque semestre, j'ai plus d'expérience que le précédent et j'acquiers des connaissances au sujet du fonctionnement de différents systèmes et technologies. Quand je regarde mes anciens projets et expériences de travail, je me rends compte de tout ce que j'ai appris!
"""
